config/routes.rb
Rails.application.routes.draw do
  root 'mytweets#index'
  resources :mytweets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mytweet.rb
class Mytweet < ApplicationRecord
  validates :content,
    length: { in: 1..140, message: 'は1文字以上140文字以下で入力してください。'},
    presence: {message: 'を入力してください。'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mytweets_controller.rb
class MytweetsController < ApplicationController
  before_action :set_mytweet, only: %i(show edit update destroy)

  def index
    @mytweets = Mytweet.all
  end

  def show
  end

  def new
    @mytweet = Mytweet.new
  end

  def edit
  end

  def create
    @mytweet = Mytweet.new(mytweet_params)
    if params[:back]
      render :new
    else
      if @mytweet.save
        redirect_to mytweets_path, notice: "ツイートを作成しました！"
      else
        render :new
      end
    end
  end

  def update
    if @mytweet.update(mytweet_params)
      redirect_to mytweets_path, notice: "ツイートを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @mytweet.destroy
    redirect_to mytweets_path, notice: "ツイートを削除しました！"
  end

  def confirm
    @mytweet = Mytweet.new(mytweet_params)
    render :new if @mytweet.invalid?
  end

  private
  def mytweet_params
    params.require(:mytweet).permit(:content)
  end

  def set_mytweet
    @mytweet = Mytweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mytweets_helper.rb
module MytweetsHelper
  def choose_new_or_eidt
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_mytweets_path
    elsif action_name == 'edit'
      mytweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mytweets | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <div><%= link_to 'Mytweets', mytweets_path %></div>
    </header>
    <div class="wrapper">
      <div class="container">
        <%= yield %>
      </div>
      <footer>
        <small>&copy;2020 Micchan.</small>
      </footer>
    </div>
  </body>
</html>

app/views/mytweets/_form.html.erb
<%= form_with(model: @mytweet, local:true, url:choose_new_or_eidt) do |form| %>
  <% if @mytweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @mytweet.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @mytweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, size: "50x10" %>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

<p>
  <%= link_to 'ツイート一覧に戻る', mytweets_path %>
</p>

app/views/mytweets/confirm.html.erb
<% provide(:title, 'ツイート確認') %>
<h1>以下の内容でツイートする。</h1>

<%= form_with(model: @mytweet, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p><strong>ツイート内容</strong></p>
  <p><%= @mytweet.content %></p>
  <div class="action">
    <%= form.submit "投稿する"  %>
    <%= form.submit "戻る", name: 'back' %>
  </div>
<% end %>

app/views/mytweets/edit.html.erb
<% provide(:title, 'ツイート編集') %>
<h2>ツイートを編集する</h2>

<%= render 'form' %>

app/views/mytweets/index.html.erb
<% provide(:title, 'ツイート一覧') %>

<p id=#notice><%= notice %></p>

<p><%= link_to 'ツイート新規作成画面へ進む', new_mytweet_path %></p>

<h1>ツイート一覧</h1>

<% @mytweets.each do |mytweet| %>
  <div class="tweet clearfix">
    <div class="content">
      <%= mytweet.content %>
    </div>
    <ul class="clearfix">
      <li><%= link_to '詳細を確認する', mytweet_path(mytweet.id)%></li>
      <li><%= link_to '本文を編集する', edit_mytweet_path(mytweet.id) %></li>
      <li><%= link_to '本文を削除する', mytweet_path(mytweet.id), method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></li>
    </ul>
  </div>
<% end %>

app/views/mytweets/new.html.erb
<% provide(:title, '新規投稿') %>
<h1>ツイート新規投稿</h1>

<%= render 'form' %>

app/views/mytweets/show.html.erb
<% provide(:title, 'ツイート詳細') %>
<h1>ツイート詳細画面</h1>

<p><strong>ツイート内容</strong></p>
  <p><%= @mytweet.content %></p>

<p>
  <%= link_to 'ツイート一覧に戻る', mytweets_path %>
</p>